from .aluno import Aluno
from .disciplina import Disciplina
from .documento import Documento
from .extensao import Extensao
from .pessoa import Pessoa
from .professor import Professor
from .projeto import Projeto
from .publicacao import Publicacao
from .helpers import Disciplina_Documento
from .helpers import Extensao_Publicaco