from .aluno import Aluno
from .disciplina import Disciplina
from .documento import Documento
from .extensao import Extensao
from .pessoa import Pessoa
from .professor import Professor
from .projeto_pesquisa import ProjetoPesquisa
from .publicacao import Publicacao
from .tipo_disciplina import TipoDisciplina
from .tipo_extensao import TipoExtensao
from .tipo_publicacao import TipoPublicacao